table CALENDARIO
	lineageTag: e2858d5f-af96-41f5-8a2a-30c53c6fc84e

	column DATA
		dataType: dateTime
		formatString: dd-mm-yy
		lineageTag: 33526fbb-1843-4bb0-b19e-d9e7b07c8760
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: b4474c8b-9f22-4978-9733-d67cb104c201
			defaultHierarchy: LocalDateTable_65cb1e60-598a-4e6a-846c-aa27b178421e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 5a660ec8-5739-4cb0-ae93-5ddc796f3a49
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: f91ea5a1-47a3-437a-a89f-6a8858138c36
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: a170af13-78d1-4530-bb0a-7b3d31eae3e4
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: d454f4b2-8048-4970-ac84-d4b572f54b2d
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	partition CALENDARIO = m
		mode: import
		source =
				let
				    Fonte = Consulta1(#date(2017, 1, 1), 1461, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "DATA"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"DATA", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([DATA]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([DATA]), type text),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Nome do Dia", each Date.DayOfWeekName([DATA]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Dia Inserido", "Trimestre", each Date.QuarterOfYear([DATA]), Int64.Type)
				in
				    #"Trimestre Inserido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

