table META_2018
	lineageTag: 8a59b01a-5013-4e08-afc0-e0b5e1541500

	column DATA
		dataType: dateTime
		formatString: Long Date
		lineageTag: 40eb74e3-04ee-46a1-8968-25d1b7e72a93
		summarizeBy: none
		sourceColumn: DATA

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TOTAL_VENDA
		dataType: int64
		formatString: 0
		lineageTag: 3d393b8f-c420-42ab-8563-83bbf13e989d
		summarizeBy: sum
		sourceColumn: TOTAL_VENDA

		annotation SummarizationSetBy = Automatic

	column VALOR_CANCELADO
		dataType: double
		lineageTag: 6f09ee86-640c-4640-a681-df7d057b577f
		summarizeBy: sum
		sourceColumn: VALOR_CANCELADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NUMERO_CUPOM_FISCAL
		dataType: int64
		formatString: 0
		lineageTag: 948789af-0ed8-4a22-a366-1779369a477d
		summarizeBy: sum
		sourceColumn: NUMERO_CUPOM_FISCAL

		annotation SummarizationSetBy = Automatic

	column VENDEDORES
		dataType: string
		lineageTag: b3e022f0-d862-4b66-9cce-9177d3a0e7cd
		summarizeBy: none
		sourceColumn: VENDEDORES

		annotation SummarizationSetBy = Automatic

	column 'FORM''PAGAMENTO'
		dataType: string
		lineageTag: 70a29220-756a-4f71-b401-af8022eca577
		summarizeBy: none
		sourceColumn: FORM'PAGAMENTO

		annotation SummarizationSetBy = Automatic

	partition META_2018 = m
		mode: import
		source = ```
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\thiag\OneDrive\Ambiente de Trabalho\3_MODULO  - POWER_BI - Expert Sênior\3_CONTROLE DE VENDAS\4_1_meta_2018.xlsx"), null, true),
				    META_2018_Sheet = Fonte{[Item="META_2018",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(META_2018_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DATA", type datetime}, {"TOTAL_VENDA", Int64.Type}, {"CAIXA_VENDEDOR", type text}, {"COD_FORMA_PGTO", type any}, {"VALOR_CANCELADO", type number}, {"NUMERO_CUPOM_FISCAL", Int64.Type}}),
				
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Tipo Alterado", "VENDEDORES", 
				    each if Text.Contains([CAIXA_VENDEDOR], "JLP") then "JULIO" 
				    else if Text.Contains([CAIXA_VENDEDOR], "VNS") then "VANESSA" 
				    else if Text.Contains([CAIXA_VENDEDOR], "VRL") then "LARISSA"
				    else if Text.Contains([CAIXA_VENDEDOR], "TH") then "THIAGO"  
				    else "VENDEDOR NÃO CADASTRADO"),
				
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada",{{"COD_FORMA_PGTO", type text}}),
				    
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado2",{{"VENDEDORES", type text}}),
				
				    #"Coluna Condicional Adicionada1" = Table.AddColumn(#"Tipo Alterado1", "FORM'PAGAMENTO", 
				    each if Text.Contains([COD_FORMA_PGTO], "1") then "DINHEIRO" 
				    else if Text.Contains([COD_FORMA_PGTO], "3") then "CARTÃO DÉBITO" 
				    else if Text.Contains([COD_FORMA_PGTO], "4") then "CARTÃO CRÉDITO" 
				    else if Text.Contains([COD_FORMA_PGTO], "##") then "CARTÃO PRESENTE" 
				    else if Text.Contains([COD_FORMA_PGTO], "$$") then "NÃO INFORMADO" 
				    else if Text.Contains([COD_FORMA_PGTO], "px") then "PIX" 
				    else "FORMA NÃO CADASTRADA"),
				   
				    #"Tipo Alterado3" = Table.TransformColumnTypes(#"Coluna Condicional Adicionada1",{{"FORM'PAGAMENTO", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado3",{"DATA", "TOTAL_VENDA", "VALOR_CANCELADO", "NUMERO_CUPOM_FISCAL", "VENDEDORES", "FORM'PAGAMENTO"}),
				    #"Tipo Alterado4" = Table.TransformColumnTypes(#"Outras Colunas Removidas",{{"DATA", type date}, {"NUMERO_CUPOM_FISCAL", type text}}),
				    #"Tipo Alterado5" = Table.TransformColumnTypes(#"Tipo Alterado4",{{"NUMERO_CUPOM_FISCAL", Int64.Type}})
				in
				    #"Tipo Alterado5"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

